write-kubeconfig-mode: "0644"
# Use VXLan overlay network for now
flannel-backend: "vxlan"
# Use k3s integrated CC as we will not use the cloud provider
disable-cloud-controller: false
# Use external cloud provider
# kubelet-arg: "cloud-provider=external"
# Labels that this Node should have
#node-label:
#  - "node_type=master"
# Cluster Domain (default: "cluster.local")
cluster-domain: "mgmt.cluster.fede.host"
# IPv4/IPv6 network CIDRs to use for pod IPs
cluster-cidr: "10.42.0.0/16"
# IPv4/IPv6 network CIDRs to use for service IPs
service-cidr: "10.43.0.0/16"
# A publicly reachable IP
node-ip: "10.0.0.82"
node-external-ip: "129.159.194.8"
tls-san: "100.71.210.177"
# Configure OIDC Authentication
#kube-apiserver-arg:
#  - "oidc-issuer-url=https://auth.fede.host"
#  - "oidc-client-id=CLIENT_ID"