apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - self-signed-issuer.yaml
  - self-signed-ca-cert.yaml
  - shared-cluster-ca.yaml
  - letsencrypt-issuer.yaml

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    includeCRDs: true
    releaseName: cert-manager
    version: v1.18.2
    repo: https://charts.jetstack.io
    valuesInline:
      crds:
        enabled: true