apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik-controller
releaseName: traefik
name: traefik
includeCRDs: true
version: 37.0.0
repo: https://traefik.github.io/charts
valuesInline:
  deployment:
    replicas: 1

  ports:
    web:
      forwardedHeaders:
        insecure: false
        trustedIPs:
          - "172.46.0.0/16"
    websecure:
      forwardedHeaders:
        insecure: false
        trustedIPs:
          - "172.46.0.0/16"
  service:
    annotations:
      metallb.io/loadBalancerIPs: 10.10.11.2

  additionalArguments:
    - "--serversTransport.rootCAs=/certs/ca.crt"
    # Traefik sometimes accesses pod ips directly
    - "--serversTransport.insecureSkipVerify=true"
    # see https://github.com/argoproj/argo-cd/issues/14607
    - "--providers.kubernetesingress.ingressendpoint.publishedservice=ingress-controllers/traefik"
