apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-operator-system
namePrefix: cloudflare-operator-

resources:
  - namespace.yaml
  - https://github.com/adyanth/cloudflare-operator.git/config/crd?ref=v0.13.1
  - https://github.com/adyanth/cloudflare-operator.git/config/rbac?ref=v0.13.1
  - https://github.com/adyanth/cloudflare-operator.git/config/manager?ref=v0.13.1
  - metrics-service.yaml

patches:
  - target:
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --metrics-bind-address=:8443
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 200Mi