---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-ddns-token
  namespace: ingress-controllers
spec:
  encryptedData:
    token: AgA5hoqbEH7LlWeJprISpSa+l0UtdcPAYzlGQ5qtkJv9B6ZETr040w8Svkb2rfEfcPd2ug80cbFWQKU9A3aTcs6IOKmaDAl4pCUDLlVUz4Fs05jlT83I+mNl1aslhBXz5OM2pe/pbQZhSsy+9e8XaVylzGaqcms9D1L8Sq5kbsbYJ5JMS3A0k6HJ+oOtjkbHL7OGjL2bri6XfmhxnH9G9hb9sid0bj3jLR/4/QlPMF6DAs1MCMmSlGkGjdFeUDHerlZV9DSvVIDkJOaK1fDn5/LCAP/O+4kqHlCqotrxckynBZTv/vBLWODcPdWTVvNW9HF7NVKw49XX5ace6VWtF+7yyVozDK4P/cWEdcvpmdo10pg0ff7XGJoSO3CXtXgshxm9RUifvWeMZ4vbJYfaJX8R1MiK0hFDIyWYPWvTHGUnTRihXlQEstuDdOkNPLsiUErBuhMQ+Mj220Rfi6+hLxl3DY3bxbUwVN9BCizccYFW7F1ao/2+cVeI1vZL+5ir3BImMtN7ZV60bRaTdEuw36qB1tnNNGdtuH5Ii3tnJU59v7o18kxoTJ2qYY/S2KSFjk8puzWnFRXtTBWcGi2zwwA7pAE6XGhh2mFZ4w/H0KR9Y6kg0eABpFUQ31xPg9p8vovNPYZaLO9m+2gina9+mAM+p8Fx3F7b4EC5wuGPXHbN+eTSbFc2hrxgRdRmu5ruRS32xBpKiRmhZ+YpNigALuR+aWR1Vh0WY3w0FEYHELFFqKaWrOqhcaMnEWND6VdPSPzrNzkPJw==
  template:
    metadata:
      creationTimestamp: null
      name: cf-ddns-token
      namespace: ingress-controllers
