apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-controllers

resources:
  - ../../../../../../base/vanilla/components/cloudflare-ddns
  - cloudflare-secret.yaml

patches:
  - target:
      kind: Deployment
      name: cloudflare-ddns
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DOMAINS
          value: "ingress.home1.mznt.fede.host"