apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-controllers

resources:
  - ../../../../../../base/vanilla/components/ingress-controller
  - traefik/private-service.yaml

generators:
  - traefik