apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - ../../../../../../base/vanilla/components/metallb
  - vms-pool.yaml
  - vms-advertisement.yaml
  - bgp-peer.yaml