apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - ../../../../../../base/vanilla/components/metallb
  - vms-pool.yaml
  - vms-advertisement.yaml
  - bgp-peer.yaml

patches:
  - target:
      kind: Deployment
      name: controller
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/args/-"
        value: "--lb-class=metallb"
  - target:
      kind: DaemonSet
      name: speaker
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/args/-"
        value: "--lb-class=metallb"