apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  # kubernetes-replicator
  - https://raw.githubusercontent.com/mittwald/kubernetes-replicator/refs/tags/v2.12.0/deploy/rbac.yaml
  - https://raw.githubusercontent.com/mittwald/kubernetes-replicator/refs/tags/v2.12.0/deploy/deployment.yaml
