apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: default-ceph-objectstore
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1


  dataPool:
    failureDomain: osd
    replicated:
      size: 1

  preservePoolsOnDelete: false

  allowUsersInNamespaces:
    - "*"

  gateway:
    port: 80
    instances: 1

  hosting:
    advertiseEndpoint:
      dnsName: "s3.mznt.eu"
      port: 80
      useTls: false
    dnsNames:
      - "s3.mznt.eu"