apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: default-ceph-pool
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
    # Disallow setting pool with replica 1, this could lead to data loss without recovery.
    # Make sure you're *ABSOLUTELY CERTAIN* that is what you want
    requireSafeReplicaSize: false
  parameters:
    compression_mode: none